# Site settings
title: Biotácora
description: >
  Bitácora de mi vida: personal y profesional. Escribo sobre biología, ciencia y las ideas que me inspiran. 
lang: es
timezone: America/Argentina/Buenos_Aires
baseurl: "/biotacora.blog" # the subpath of your site, e.g. /blog/
url: "https://lsduenas14.github.io" # the base hostname & protocol for your site

author:
  fullname: Salomé Dueñas
  github: https://github.com/lsduenas14
  linkedin: https://www.linkedin.com/in/salom%C3%A9-due%C3%B1as-5603b7343/
  email: scduenas14@hotmail.com
  


# Syntax highlighting
highlightstyle: 'agate'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]


# Build settings
highlighter: null
markdown: kramdown
